# Generated by Django 5.2 on 2025-04-26 19:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSYPT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('ctitation', models.TextField(blank=True, null=True)),
                ('totalquestions', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTHist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSYPTItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('item_num_1', models.TextField()),
                ('item_num_2', models.TextField(blank=True, null=True)),
                ('item_num_3', models.TextField(blank=True, null=True)),
                ('facet', models.TextField(blank=True, null=True)),
                ('keyed', models.TextField(blank=True, default='+', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTResultDef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.TextField()),
                ('score_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTUserAttempt',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSYPTDomain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('psy_pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.psypt')),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTFacet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facet', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('psy_pt_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.psyptdomain')),
            ],
        ),
    ]
