# Generated by Django 5.2 on 2025-04-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psypthist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psyptitem',
            name='psy_pt_domain',
            field=models.ManyToManyField(to='mainapp.psyptdomain'),
        ),
        migrations.AddField(
            model_name='psyptresultdef',
            name='psy_pt_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.psyptdomain'),
        ),
        migrations.AddField(
            model_name='psyptuserattempt',
            name='psy_pt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.psyptitem'),
        ),
        migrations.AddField(
            model_name='psyptuserattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.psypthist'),
        ),
        migrations.AddField(
            model_name='psyptuserattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
